name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - master  # Set branch to deploy from

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true    # Required for Sass/SCSS support

      - name: Setup Theme
        run: |
          git clone https://github.com/thegeeklab/hugo-geekdoc.git themes/hugo-geekdoc

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public